### ISSUE TITLE
Update all class names to use namespaced classes

### ISSUE THREAD

**Issue by gblair** [castiron/cicbase#4]
@zdavis you suggested this, and I think it's a good idea.  Currently we have a mix of old and new style class names in this extension.  The main ouchy will be the need to update viewhelper namespaces in existing Fluid views.  If we want to mitigate that problem, we could set up some kind of legacy class mapping, but I see that as a low priority, and would almost rather we enforce the modern class names by introducing this little bit of pain into the system.

@lthurston and @psoots what say you guys?  @psoots and I had a little chat about this a few months back in the context of #3.  This would encompass that issue, and get class names straightened out once and for all.

**Comment by zdavis** [comment]
I'm thinking we should close this, unless anyone objects?
