### ISSUE TITLE
Why use setter to define tstamp?

### ISSUE THREAD

**Issue by ursbraem** [castiron/cicbase#6]
Hi!

I was looking for a way to use the tstamp / crdate fields in extbase and found your repo, and it worked! Thanks! I posted what I made from your snippet on http://stackoverflow.com/questions/13733546/how-to-use-standard-fields-like-crdate-and-cruser-id-with-typo3-and-extbase/29390915#29390915 

What I don't understand is why you use the setter in:

	/**
	 * @param int $tstamp
	 */
	public function setTstamp($tstamp) {
		$this->tstamp = $tstamp;
	}

	/**
	 * @return int
	 */
	public function getTstampObj() {
		$out = new \DateTime();
		$out->setTimestamp($this->tstamp);
		return $out;
	}

Other examples on the web just to `return $this->tstamp` (and don't work)..

**Comment by ursbraem** [comment]
Never mind, I got it all wrong. Obviously, you use the TstampObj for other purposes. To just read the tstamp to fluid, I don't need that. Thanks for sharing!

**Comment by zdavis** [comment]
Glad to hear that our extension was helpful! Don't hesitate to let us know if you have any other questions.

best,
Zach
